kind = "mobile"
previewPath = "/"
title = "Wearwise"
version = "1.0.0"
id = "artifacts/wearwise"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 19818

[services.development]
run = "pnpm --filter @workspace/wearwise run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/wearwise", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/wearwise", "run", "serve" ]

[services.env]
PORT = "19818"
BASE_PATH = "/"
